schema: schema.graphql

exec:
  filename: ./../../pkg/graphql/gqlgen/generated.go

model:
  filename: ./../../pkg/graphql/models/generated.go

models:
  Restaurant:
    fields:
      dishes:
        resolver: true
