schema: schema.graphql

exec:
  filename: ./../../pkg/graphql/gqlgen/generated.go

model:
  filename: ./../../pkg/graphql/models/generated.go

models:
  Dish:
    fields:
      restaurant:
        resolver: true
      category:
        resolver: true

  Restaurant:
    fields:
      dishes:
        resolver: true
      category:
        resolver: true
  
  Category:
    fields:
      dishes:
        resolver: true